# Generated by Django 3.2 on 2024-01-25 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20240123_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlesmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='titles.categoriesmodel', verbose_name='Категория произведения'),
        ),
    ]
