# Generated by Django 3.2 on 2024-01-24 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('titles', '__first__'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentModel',
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewModel',
        ),
    ]
