# Generated by Django 3.2 on 2024-01-24 10:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_auto_20240124_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='created',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='titles',
            new_name='review',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='author',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviews',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name='Дата добавления',
            ),
            preserve_default=False,
        ),
    ]
