# Generated by Django 3.2 on 2024-01-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20240125_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='review',
            new_name='review_id',
        ),
    ]
